#baseURL = "https://unixmagic.net/"
baseURL = "/"
relativeURLs = true
uglyURLs = false
languageCode = "en-us"
title = "Unix Magic Poster Annotations"
enableGitInfo = true

[params]
  description = "An interactive, annotated guide to every reference on the classic UNIX Magic poster by Gary Overacre."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
